name: maps_launcher
description: Simple Flutter plugin to open the maps application (or browser) on all platforms.
version: 2.4.0
homepage: https://github.com/pikaju/flutter-maps-launcher

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.maps_launcher
        pluginClass: MapsLauncherPlugin
      ios:
        pluginClass: MapsLauncherPlugin
      windows:
        pluginClass: MapsLauncherPlugin
      macos:
        pluginClass: MapsLauncherPlugin
      linux:
        pluginClass: MapsLauncherPlugin
      web:
        pluginClass: MapsLauncherWeb
        fileName: maps_launcher_web.dart
